const actionTypes =
{
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	GET_DATA: "GET_DATA",
	SET_LOADING: "SET_LOADING",	
	SET_TRENDING_KEYWORD: "SET_TRENDING_KEYWORD",	
	ADD_FAVORITE: "ADD_FAVORITE",	
	DELETE_FAVORITE: "DELETE_FAVORITE",	
	ERROR:"ERROR"
};

export default actionTypes;